version: "3"
services:
  ipfs:
    env_file:
      - ipfs-service.env
    build: './ipfs'
    volumes:
      - "~/.ipfs-service/export:/export"
      - "~/.ipfs-service/data:/data/ipfs"
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5001:5001"
      - "8080:8080"
