---
- name: Upload new NGINX config
  hosts: ipfs-server
  tasks:
    - name: Update the NGINX config
      become: True
      synchronize:
        src: nginx.conf.d/production-proxy.conf
        dest: /docker/etc/nginx/conf.d/proxy.conf

    - name: Restart the Docker containers
      docker_service:
        project_src: /home/ec2-user/ipfs-service/docker
        build: yes
        state: present
        restarted: True
