version: "3"
services:
  ipfs:
    build: './ipfs'
    restart: on-failure
    env_file:
      - ../ipfs-service.env
    volumes:
      - "/docker/var/ipfs/export:/export"
      - "/docker/var/ipfs/data:/data/ipfs"
    ports:
      - 4001:4001
      - 8080:8080
  webrtcstar:
    build: './p2p-webrtc-star'
    restart: on-failure
  nginx:
    build: './nginx-custom'
    restart: on-failure
    volumes:
      - /docker/certs/letsencrypt:/etc/letsencrypt:ro
      - /docker/var/log/nginx:/var/log/nginx
      - /docker/var/www/letsencrypt:/var/www/letsencrypt
      - /docker/etc/nginx/conf.d:/etc/nginx/conf.d/ipfs-service
    ports:
      - 80:80
      - 443:443
      - 5001:5001
      - 9090:9090
