version: "3"
services:
  whisper_mainnet:
    build: './whisper'
    restart: always
    volumes:
      - "/docker/var/whisper_mainnet:/root/.ethereum"
  whisper_rinkeby:
    build: './whisper'
    restart: always
    volumes:
      - "/docker/var/whisper_rinkeby:/root/.ethereum"
  whisper_ropsten:
    build: './whisper'
    restart: always
    volumes:
      - "/docker/var/whisper_ropsten:/root/.ethereum"
  ipfs:
    build: './ipfs'
    restart: always
    env_file:
      - ../ipfs-service.env
    volumes:
      - "/docker/var/ipfs/export:/export"
      - "/docker/var/ipfs/data:/data/ipfs"
    ports:
      - 4001:4001
      - 8080:8080
  nginx:
    build: './nginx-custom'
    restart: always
    volumes:
      - /docker/certs/letsencrypt:/etc/letsencrypt:ro
      - /docker/var/log/nginx:/var/log/nginx
      - /docker/var/www/letsencrypt:/var/www/letsencrypt
      - /docker/etc/nginx/conf.d:/etc/nginx/conf.d/ipfs-service
    ports:
      - 80:80
      - 443:443
      - 5001:5001
      - 9090:9090
      - 9091:9091
      - 9546:9546
      - 10546:10546
      - 11546:11546
